remote_theme: pages-themes/leap-day@v0.2.0
#theme: jekyll-theme-hacker

title: [Abubakar Riaz]
description: [Solution Architect @ PGC |âš¡ï¸xJazz | Full Stack .Net DeveloperğŸ‘¨â€ğŸ’»| SQL Server Trainer @ EVSğŸ“| Azure DevOps ğŸš€]


show_downloads: [false]
google_analytics: [Your Google Analytics tracking ID]